# -*- coding: utf-8 -*-
"""ECON441B LAB1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SAzlRaUjK5BaOl7AEfPaiTcGgD_o6HJS
"""

import pandas as pd
from google.colab import drive
drive.mount('/content/gdrive/',force_remount = True)
import matplotlib.pyplot as plt

df = pd.read_csv("/content/gdrive/MyDrive/ECON441B/Trade.csv")

df.set_index("recieve_time",inplace = True)

df.index = pd.to_datetime(df.index)
df.head()

plt.figure(figsize = (12,5))
plt.plot(df['price'])
plt.title('Trade INDEX')
plt.xlabel("time")
plt.ylabel('balance')
plt.grid()
plt.show()

# The graph shows the price of cs2203 and c2203 (2 kinds of traded good) on the future market from November 2021 to December 2021.
# We can observe that the price movement have a cyclic feature. They also have have a upper and lower price bound of 3200 and 2700 repectively.